"""Utilities for duplicating the EvOSys lookup behavior.

This module builds on the parsed CSVs from other scripts. In particular,
it reads `evo9_01.csv` (the EvO9.01 export) and reproduces the SUMIF
calculations EvOSys performs against columns A and C to populate the
estimated values for each line/stop group. The output CSV has two
columns: `["Line", "Estimated"]`.
"""

from __future__ import annotations

import argparse
import csv
import sys
import zipfile
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import xml.etree.ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"

DEFAULT_CALIBRATION = Path("calibration/Boston_Regional_STOPS Calibration Report_2050.xlsx")
DEFAULT_EVO9_CSV = Path("evo9_01.csv")
EVOSYS_SHEET = "EvOSys"
EVO901_SHEET = "EvO9.01"


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replicate EvOSys SUMIF lookups using the evo9_01.csv data."
    )
    parser.add_argument(
        "--calibration-workbook",
        type=Path,
        default=DEFAULT_CALIBRATION,
        help="Workbook that hosts EvOSys/EvO9.01 (default: 2050 report)",
    )
    parser.add_argument(
        "--evosys-sheet",
        default=EVOSYS_SHEET,
        help="Sheet name containing the EvOSys layout (default: EvOSys)",
    )
    parser.add_argument(
        "--evo9-csv",
        type=Path,
        default=DEFAULT_EVO9_CSV,
        help="CSV generated by evo901.py (default: evo9_01.csv)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("evosys_estimates.csv"),
        help='Destination CSV path (default: "evosys_estimates.csv")',
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    label_specs = extract_line_specs(args.calibration_workbook, args.evosys_sheet)
    if not label_specs:
        sys.stderr.write("No EvO9.01 SUMIF rows detected in EvOSys.\n")
        return 1

    stop_totals = load_totals_by_stop(args.evo9_csv)
    line_map, group_map = load_stop_mappings(args.calibration_workbook, EVO901_SHEET)

    line_totals = aggregate_by_label(line_map, stop_totals)
    group_totals = aggregate_by_label(group_map, stop_totals)

    rows: List[List[str]] = []
    missing: List[str] = []
    for label, reference in label_specs:
        totals = line_totals if reference == "C" else group_totals
        value = totals.get(label)
        if value is None:
            missing.append(label)
        rows.append([label, format_number(value)])

    write_csv(args.output, rows)
    sys.stdout.write(f"Wrote {len(rows)} rows to {args.output}\n")

    if missing:
        sys.stderr.write(
            f"Warning: {len(missing)} labels had no matching rows in evo9_01.csv "
            f"({', '.join(missing[:5])}{'...' if len(missing) > 5 else ''})\n"
        )
    return 0


def write_csv(path: Path, rows: Sequence[Sequence[str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["Line", "Estimated"])
        writer.writerows(rows)


def extract_line_specs(
    workbook_path: Path, sheet_name: str
) -> List[Tuple[str, str]]:
    specs: List[Tuple[str, str]] = []
    with zipfile.ZipFile(workbook_path) as archive:
        sheet = _load_sheet(archive, sheet_name)
        shared = _load_shared_strings(archive)
        sheet_data = sheet.find("m:sheetData", NS)
        if sheet_data is None:
            return specs

        for row in sheet_data:
            cells = _extract_row_cells(row, shared, include_formulas=True)
            formula = cells.get(("D", "formula"))
            label = cells.get(("A", "value"))
            if not (
                formula
                and "SUMIF" in formula
                and "EvO9.01" in formula
                and label
                and label.strip()
            ):
                continue
            if "!C:C" in formula:
                reference = "C"
            elif "!A:A" in formula:
                reference = "A"
            else:
                continue
            specs.append((label.strip(), reference))
    return specs


def load_totals_by_stop(csv_path: Path) -> Dict[str, float]:
    totals: Dict[str, float] = {}
    with csv_path.open(encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            stop_id = (row.get("STOP_ID1") or "").strip()
            total = to_number(row.get("TOTAL"))
            if not stop_id or total is None:
                continue
            totals[stop_id] = totals.get(stop_id, 0.0) + total
    return totals


def load_stop_mappings(
    workbook_path: Path, sheet_name: str
) -> Tuple[Dict[str, List[str]], Dict[str, List[str]]]:
    line_members: Dict[str, List[str]] = defaultdict(list)
    group_members: Dict[str, List[str]] = defaultdict(list)
    with zipfile.ZipFile(workbook_path) as archive:
        sheet = _load_sheet(archive, sheet_name)
        shared = _load_shared_strings(archive)
        sheet_data = sheet.find("m:sheetData", NS)
        if sheet_data is None:
            return {}, {}

        for row in sheet_data:
            cells = _extract_row_cells(row, shared, include_formulas=False)
            stop_id = cells.get(("H", "value"))
            if not stop_id:
                continue
            line_value = (cells.get(("C", "value")) or "").strip()
            group_value = (cells.get(("A", "value")) or "").strip()
            if line_value:
                line_members[line_value].append(stop_id)
            if group_value:
                group_members[group_value].append(stop_id)
    return dict(line_members), dict(group_members)


def aggregate_by_label(
    mapping: Dict[str, List[str]], totals: Dict[str, float]
) -> Dict[str, float]:
    aggregates: Dict[str, float] = defaultdict(float)
    for label, stop_ids in mapping.items():
        subtotal = 0.0
        has_value = False
        for stop_id in stop_ids:
            total = totals.get(stop_id)
            if total is None:
                continue
            subtotal += total
            has_value = True
        if has_value:
            aggregates[label] = subtotal
    return dict(aggregates)


def _extract_row_cells(
    row: ET.Element,
    shared_strings: Sequence[str],
    include_formulas: bool = False,
) -> Dict[Tuple[str, str], str]:
    result: Dict[Tuple[str, str], str] = {}
    for cell in row.findall("m:c", NS):
        column = "".join(ch for ch in cell.attrib.get("r", "") if ch.isalpha()).upper()
        if not column:
            continue
        value = _cell_value(cell, shared_strings)
        if value is not None:
            result[(column, "value")] = value
        if include_formulas:
            formula_node = cell.find("m:f", NS)
            if formula_node is not None and formula_node.text:
                result[(column, "formula")] = formula_node.text
    return result


def _cell_value(cell: ET.Element, shared_strings: Sequence[str]) -> str | None:
    cell_type = cell.attrib.get("t")
    if cell_type == "inlineStr":
        text_parts = [t.text or "" for t in cell.findall("m:is/m:t", NS)]
        return "".join(text_parts).strip()
    value_node = cell.find("m:v", NS)
    if value_node is None:
        return None
    if cell_type == "s":
        index = int(value_node.text or "0")
        if 0 <= index < len(shared_strings):
            return shared_strings[index]
        return None
    return value_node.text


def _load_shared_strings(archive: zipfile.ZipFile) -> List[str]:
    try:
        xml_data = archive.read("xl/sharedStrings.xml")
    except KeyError:
        return []
    root = ET.fromstring(xml_data)
    strings = []
    for si in root.findall("m:si", NS):
        strings.append("".join(t.text or "" for t in si.findall(".//m:t", NS)))
    return strings


def _load_sheet(archive: zipfile.ZipFile, sheet_name: str) -> ET.Element:
    workbook = ET.fromstring(archive.read("xl/workbook.xml"))
    relationships = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
    rel_map = {
        rel.attrib["Id"]: rel.attrib["Target"]
        for rel in relationships.findall(f"{{{REL_NS}}}Relationship")
    }
    for sheet in workbook.findall("m:sheets/m:sheet", NS):
        if sheet.attrib.get("name") == sheet_name:
            sheet_rid = sheet.attrib.get(
                "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id"
            )
            if sheet_rid is None:
                break
            target = rel_map.get(sheet_rid)
            if target is None:
                break
            return ET.fromstring(archive.read(f"xl/{target}"))
    raise KeyError(f"Sheet {sheet_name} not found")


def to_number(value: str | None) -> float | None:
    if value is None:
        return None
    text = str(value).replace(",", "").strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def format_number(value: float | None) -> str:
    if value is None:
        return ""
    if abs(value - round(value)) < 1e-9:
        return str(int(round(value)))
    return f"{value:.6f}".rstrip("0").rstrip(".")


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
